### ISSUE TITLE
Could not locate the bindings file

### ISSUE THREAD

**Issue by parautenbach** [rsg98/wiring-pi#10]
I'm getting the following error on Raspbian Buster running Node.js v10.

```
$ node
> require("node-wiring-pi");
Thrown:
{ Error: Could not locate the bindings file. Tried:
 → /home/pi/node_modules/node-wiring-pi/build/nodeWiringPi.node
...
```

The problem I'm debugging is a fresh homebridge installation with the homebridge-gpio-device plugin. The latest version of this plugin asks fro node-wiring-pi v0.0.4 while the latest is v0.0.5. 

The error above first appeared when starting homebridge from the command-line, so I searched for a way to reproduce the error in a minimal way (i.e. the above example) to show node-wiring-pi doesn't load correctly. 

I've tried to stick to node best practices by not running npm commands with sudo. 

I've tried installing a specific version of wiringpi as detailed here: https://www.npmjs.com/package/homebridge-gpio-device

I've also tried the latest version, 2.50, of wiringpi.

None of this seems to make any difference.

As it stands, a vanilla installation of node-wiring-pi fails as I've shown at the beginning above. From the little I understand from the bindings, is that it's something that needs to be compiled with gyp. I've never used this and don't know what it does exactly, but it seems gyp and node-gyp are both correctly installed. 

I'm quite stumped as this issue has kept me busy for days playing with my hobby RPI at home. 

Any help or pointers would be appreciated.

**Comment by parautenbach** [comment]
Further information, if it can help: This is what I get if I try to run `node-gyp rebuild`:

```
../../nan/nan_object_wrap.h:65:61:   required from here
/home/pi/.cache/node-gyp/10.17.0/include/node/v8.h:9502:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
make: *** [nodeWiringPi.target.mk:118: Release/obj.target/nodeWiringPi/src/wiringPi.o] Error 1
make: Leaving directory '/home/pi/.npm-global/lib/node_modules/homebridge-gpio-device/node_modules/node-wiring-pi/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pi/.npm-global/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.19.75-v7+
gyp ERR! command "/usr/bin/node" "/home/pi/.npm-global/bin/node-gyp" "configure" "build"
gyp ERR! cwd /home/pi/.npm-global/lib/node_modules/homebridge-gpio-device/node_modules/node-wiring-pi
gyp ERR! node -v v10.17.0
gyp ERR! node-gyp -v v6.0.1
gyp ERR! not ok
```

**Comment by parautenbach** [comment]
I can't explain why, as I didn't go through every line of code, but what I did to get this working was to navigate to the directory with the `Makefile`, run `make` followed by `node-gyp rebuild`. I would love to know why if there is something with a deeper understanding of this.
